# Generated by Django 6.0 on 2026-01-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ky',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_en',
            field=models.CharField(choices=[('люкс', 'люкс'), ('полулюкс', 'полулюкс'), ('эконом', 'эконом'), ('семейный', 'семейный'), ('одноместный', 'одноместный')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_ky',
            field=models.CharField(choices=[('люкс', 'люкс'), ('полулюкс', 'полулюкс'), ('эконом', 'эконом'), ('семейный', 'семейный'), ('одноместный', 'одноместный')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_ru',
            field=models.CharField(choices=[('люкс', 'люкс'), ('полулюкс', 'полулюкс'), ('эконом', 'эконом'), ('семейный', 'семейный'), ('одноместный', 'одноместный')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_ky',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
