# Generated by Django 6.0 on 2026-01-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_city_city_name_en_city_city_name_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name_ky',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name_ru',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_en',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_ky',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type_ru',
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_ky',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='street_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_description_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_description_ru',
            field=models.TextField(null=True),
        ),
    ]
