# Generated by Django 6.0 on 2026-01-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_remove_hotel_hotel_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='service',
        ),
        migrations.AddField(
            model_name='hotel',
            name='service',
            field=models.ManyToManyField(to='booking_app.service'),
        ),
    ]
